import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport:{width:375,height:812} })
p.on('console', m => console.log('CONSOLE', m.type(), m.text().slice(0,200)))
p.on('pageerror', e => console.log('PAGEERROR', e.message.slice(0,300)))
await p.goto('http://localhost:5199', { waitUntil:'domcontentloaded' })
await p.waitForTimeout(3000)
console.log('URL', p.url())
console.log('TEXT', (await p.evaluate(()=>document.body.innerText)).slice(0,600))
await b.close()
